# Generated by Django 5.0 on 2026-05-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='project_link',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='Portfolio Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
